Work-in-progress: EveryAction events
sunrisemovement/events-map pull request #3
Opened 2020-07-13 17:05 UTC by asross

2020-09-18 21:17 UTC, BrianHicks requested changes
Looking good! A lot of these comments are just me marking things and asking questions. The only thing I think we would really need to address before release is changing from a recursive implementation to an iterative one.

2020-09-18 21:17 UTC, BrianHicks commented on mobilize_america.rb
> +  # @sunrisemovement.org emails.
this is a :100: comment!

2020-09-18 21:17 UTC, BrianHicks commented on every_action.rb
> +  MAX_ITERS = 100
🎨 maybe MAX_PAGES? I didn't know what this was for until I saw it used in the methods below.

2020-09-18 21:17 UTC, BrianHicks commented on every_action.rb
> +  def events_request(url=nil, iter=0)
why is this recursive instead of iterative? Could be something like:

```ruby
url = "https://..." # url we have now
events = []

MAX_ITERS.each do
  # make request, appending to events
  url = resp["nextPageLink"]
  break if url.nil?
end

return events
```

I don't think Ruby will do tail-call optimization so an iterative implementation is stack-safe, as well.

2020-09-18 21:17 UTC, BrianHicks commented on every_action.rb
> +  def events_request(url=nil, iter=0)
we could also remove the limit if we want to get all of the events in the dataset and are confident we won't run out of API quota by doing so. I guess that'd just be like `while !url.nil?` instead of `MAX_ITERS.each` or something? I always have to look up non-map iteration things in Ruby 😆

2020-09-19 11:17 UTC, asross commented on every_action.rb
> +  MAX_ITERS = 100
Agreed!

2020-09-19 11:19 UTC, asross commented on every_action.rb
> +    # defaulting to Sunrise
I see, that makes sense. I can try to make comments more focused on the reasons for the implementation, and maybe remove the "what"-based comments when it's self-explanatory.

2020-09-19 11:22 UTC, asross commented on every_action.rb
> +  def events_request(url=nil, iter=0)
Good point... I think I just used recursion because it's the first method the occurred to me, but a loop is probably better 👍 

And yeah, we could just get rid of the max iteration limit, I guess. It shouldn't be a problem in practice.

2020-09-19 11:27 UTC, asross commented on every_action.rb
> +    locations.first || {}
So, it is possible, but doesn't appear to happen in practice (or at least not any time I've checked).

I guess this brings up a larger issue which is that events might have multiple values for several fields (e.g. registration URL and timeslot as well as location), but I think it's different between EveryAction and Mobilize. Since handling that requires more than just backend changes, though (i.e. updating the HTML to render multiple pins and cards), maybe let's table it for a later PR!

2020-09-19 19:20 UTC, asross commented on every_action.rb
> +    url ||= "https://api.securevan.com/v4/events?startingAfter=#{Date.today-20}&$expand=onlineforms,locations,codes,shifts,roles,notes"
this was fixed to be `Date.today-1` in a subsequent commit, I had temporarily changed it for testing and accidentally committed it

2020-09-19 19:22 UTC, asross commented on every_action.rb
> +    url ||= "https://api.securevan.com/v4/events?startingAfter=#{Date.today-20}&$expand=onlineforms,locations,codes,shifts,roles,notes"
(According to the [API docs](https://developers.everyaction.com/van-api#events-get-events), that would correspond to getting events whose start dates are today or later)

2020-09-21 10:11 UTC, BrianHicks approved these changes
Thank you!

2020-09-21 11:29 UTC, merged